<?php

namespace AppBundle\Repository\Note;
use AppBundle\Entity\Note\Label;

/**
 * LabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabelRepository extends \Doctrine\ORM\EntityRepository
{

    public function createFromPayload(array $payload)
    {
        $label = new Label();
        $this->update($label, $payload);

        $this->getEntityManager()->persist($label);
        $this->getEntityManager()->flush();

        return $label;
    }

    public function updateFromPayload(Label $label, array $payload)
    {
        $this->update($label, $payload);
        $this->getEntityManager()->flush();

        return $label;
    }

    private function update(Label $label, array $payload)
    {
        $label->setName($payload['name']);
    }
}
